// <auto-generated />
namespace InsuranceRestSerwer.Migrations.Insurance
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class backtoErlierversion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(backtoErlierversion));
        
        string IMigrationMetadata.Id
        {
            get { return "201801102103404_backtoErlierversion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
